const products = [
	{
		imgUrl: '/images/products/syltherine.png',
		name: 'Syltherine',
		description: 'Stylish cafe chair',
		price: 3500000,
		discount: 30,
		discountPrice: 2500000,
		isNew: false,
	},
	{
		imgUrl: '/images/products/leviosa.png',
		name: 'leviosa',
		description: 'Stylish cafe chair',
		price: 2500000,
		discount: 0,
		discountPrice: 0,
		isNew: false,
	},
	{
		imgUrl: '/images/products/lolito.png',
		name: 'Lolito',
		description: 'Luxury big sofa',
		price: 14000000,
		discount: 50,
		discountPrice: 7000000,
		isNew: false,
	},
	{
		imgUrl: '/images/products/respira.png',
		name: 'Respira',
		description: 'Minimalist fan',
		price: 500000,
		discount: 0,
		discountPrice: 0,
		isNew: true,
	},
	{
		imgUrl: '/images/products/grifo.png',
		name: 'Grifo',
		description: 'Night lamp',
		price: 1500000,
		discount: 0,
		discountPrice: 0,
		isNew: false,
	},
	{
		imgUrl: '/images/products/muggo.png',
		name: 'Muggo',
		description: 'Small mugg',
		price: 150000,
		discount: 0,
		discountPrice: 0,
		isNew: true,
	},
	{
		imgUrl: '/images/products/pingky.png',
		name: 'Pingky',
		description: 'Cute bed set',
		price: 14000000,
		discount: 50,
		discountPrice: 7000000,
		isNew: false,
	},
	{
		imgUrl: '/images/products/potty.png',
		name: 'Potty',
		description: 'Minimalist flower pot',
		price: 5000000,
		discount: 0,
		discountPrice: 0,
		isNew: true,
	}
]

export default products;